
FLAGS= -Wall -g

CC=gcc

all: sort txtSearch

sort: mainSort.o sort.o
	 $(CC) $(FLAGS) -o sort mainSort.o sort.o

 txtSearch: searchMain.o txtSearch.o
	$(CC) $(FLAGS) -o txtSearch searchMain.o txtSearch.o

mainSort.o: mainSort.c
 	 $(CC) $(FLAGS) -c mainSort.c
	 
 searchMain.o: searchMain.c
 	 $(CC) $(FLAGS) -c searchMain.c
	 
 sort.o: sort.c sort.h
 	$(CC) $(FLAGS) -c sort.c

 txtSearch.o: txtSearch.c txtSearch.h
 	$(CC) $(FLAGS) -c txtSearch.c



 .PHONY:	clean all

 clean:
rm -f *.o sort txtSearch
